language: python
sudo: false
python:
- '2.7'
addons:
        apt:
                packages:
                        texlive-latex-base
                        #texlive-fonts-recommended
                        #texlive-fonts-extra
                        #texlive-latex-extra
before_install:
- git config --global user.email "donotreply@travis.ci"
- git config --global user.name "travisci"
- git config --global credential.helper store --file=$HOME/.git-credentials
- echo "https://${GH_USER}:${GH_TOKEN}@github.com" > $HOME/.git-credentials
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- chmod +x miniconda.sh
- "./miniconda.sh -b -p /home/travis/mc"
- export PATH=/home/travis/mc/bin:$PATH
install:
- export GIT_FULL_HASH=`git rev-parse HEAD`
- conda config --set always_yes true
- conda config --set show_channel_urls true
- conda config --add channels lightsource2
- conda config --add channels bokeh
- conda config --add channels asmeurer
- conda update conda
- conda install conda-build
- conda create -n testenv pip python=$TRAVIS_PYTHON_VERSION ipywidgets "numpy<1.10"
  jsonschema jinja2 sphinx pyyaml prettytable boltons sphinx-bootstrap-theme
  pandoc
- source activate testenv
script:
- cd $TRAVIS_BUILD_DIR && make html
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  cd $TRAVIS_BUILD_DIR && make github; fi;
after_success:
env:
  global:
  - GH_USER=waynelewis
  - secure: vjBaIbDvZDNZxxzLnI/zDM6KT4IUA9uhhe/C2wYU8d09FW4yuIYpTJqwCyRCuuYvXBGej9LP9ZG/0+qO+4T4QfDCVpQKymBcaPY0ccX0MuNcWZTrCpYOGdykwhg8L/2bTu4ovrW/BaF2Ppy6MSDKZeavKlNqzxd4PGZc9lHBxa6gcLvIw00CqIJP3lO3fZCCEUssTIPzYjNHKQ47Ip/Lw3e66ptM2Mxg1jP/6px5zUMxnNWkiNyU6Fi+Ohl+w59Ey5EvXCcVgQiUk5giOW3XcHYsMWx8GBq5KkP763XQ1bUzFOEdo5Y8CuDQmLL29HFEGKk7oZapOAL8x9+zB7chFzTIhq9OSX3ry7+VOCStykFYOWZ2PuG7sO0kiwatwWfpslpEjZXs/B1Chvd+5MfHlvmcq430Q4nI8bkd5MEvGaECLQ32pTVBWWxQ7Btaqr3KtLt1r6virUSnPNpAbMiLLOuscCacMJ4Q4d9D9Qfd0kdUnhl5RFY9X61Xidfzi1nhSyEuAUUwVox84nrWERQxMbQlqZd38NPQHgAhlfoN6XfVoH0LKAyhm4vLkJ8NTRmCjlEp2tOTilTpqpryglm0oR/0BXPwbx5YyKhm6+lS/m1ZGm9vjP0mZJkdOu4T0TnvJM4yOdjgK8DF8zsYRHPm90n3stj9sG9KMfj9+LSFTpc=
