language: python
sudo: false
python:
- '2.7'
before_install:
- git config --global user.email "donotreply@travis.ci"
- git config --global user.name "travisci"
- git config --global credential.helper store --file=$HOME/.git-credentials
- echo "https://${GH_USER}:${GH_TOKEN}@github.com" > $HOME/.git-credentials
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- chmod +x miniconda.sh
- "./miniconda.sh -b -p /home/travis/mc"
- export PATH=/home/travis/mc/bin:$PATH
  #- sudo apt-get update
  #- sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng
install:
- export GIT_FULL_HASH=`git rev-parse HEAD`
- conda config --set always_yes true
- conda config --set show_channel_urls true
- conda config --add channels lightsource2
- conda config --add channels bokeh
- conda config --add channels asmeurer
- conda update conda
- conda install conda-build
  #- conda create -n testenv pip python=$TRAVIS_PYTHON_VERSION six "numpy<1.10" pandas
  #h5py coverage jsonschema jinja2 sphinx pyyaml ipywidgets tzlocal prettytable boltons
  #pymongo=2.9 pims=0.3.3 tifffile databroker sphinx-bootstrap-theme pandoc
- conda create -n testenv pip python=$TRAVIS_PYTHON_VERSION six "numpy<1.10" 
  coverage jsonschema jinja2 sphinx pyyaml ipywidgets prettytable boltons
  pims=0.3.3 sphinx-bootstrap-theme pandoc
- source activate testenv

script:
- cd $TRAVIS_BUILD_DIR && make html 
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  cd $TRAVIS_BUILD_DIR && make github GIT_MF=1; fi;
after_success:
env:
  global:
  - GH_USER=waynelewis
    #- MDS_HOST=localhost
    #- MDS_DATABASE=test
    #- MDS_TIMEZONE=US/Eastern
    #- FS_HOST=localhost
    #- FS_DATABASE=test
